function KinematicDatafromPMKS = importPKMS(filename, dataLines)
%IMPORTFILE Import data from a text file
%  KINEMATICDATAFROMPMKS = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  KINEMATICDATAFROMPMKS = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  KinematicDatafromPMKS = importfile("C:\Users\kohle\OneDrive\Documents\UT\ME 380R Robot Mechanism Design\Final Project\KinematicDatafromPMKS.51.50.8.29.3.2023.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2023 12:58:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 43, "Encoding", "UTF16-LE");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimeSteps", "x_0", "y_0", "Vx_0", "Vy_0", "Ax_0", "Ay_0", "x_1", "y_1", "Vx_1", "Vy_1", "Ax_1", "Ay_1", "x_2", "y_2", "Vx_2", "Vy_2", "Ax_2", "Ay_2", "x_3", "y_3", "Vx_3", "Vy_3", "Ax_3", "Ay_3", "x_4", "y_4", "Vx_4", "Vy_4", "Ax_4", "Ay_4", "angle_ground", "angVel_ground", "angAccel_ground", "angle_input", "angVel_input", "angAccel_input", "angle_coupler", "angVel_coupler", "angAccel_coupler", "angle_output", "angVel_output", "angAccel_output"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
KinematicDatafromPMKS = readtable(filename, opts);

end